// scripts/generate-env.mjs
import { config as loadDotenv } from 'dotenv';
import { writeFileSync, existsSync } from 'node:fs';
import { z } from 'zod';

loadDotenv(); // no-op if .env doesn't exist (Docker/CI inject real env vars directly)

const schema = z.object({
  API_BASE_URL: z.string().url().default('http://127.0.0.1:3000'),
  SITE_URL: z.string().url().default('http://localhost:4200'),
});

const result = schema.safeParse(process.env);
if (!result.success) {
  console.error('Invalid environment configuration for client build:');
  for (const issue of result.error.issues) {
    console.error(`  - ${issue.path.join('.')}: ${issue.message}`);
  }
  process.exit(1);
}

const { API_BASE_URL, SITE_URL } = result.data;

const content = `// AUTO-GENERATED by scripts/generate-env.mjs — do not edit by hand.
export const environment = {
  apiBaseUrl: '${API_BASE_URL}',
  siteUrl: '${SITE_URL}',
};
`;

writeFileSync(new URL('../src/environments/environment.ts', import.meta.url), content);
console.log(`Generated src/environments/environment.ts (apiBaseUrl=${API_BASE_URL})`);

if (!existsSync(new URL('../.env', import.meta.url))) {
  console.log('No .env found — used defaults/placeholders above (fine for Docker build/CI).');
}
